name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip==22.3.1
        python3 -m pip install --user pipx==1.1.0
        python3 -m pipx ensurepath
        pipx install poetry==1.3.2
        pipx install nox==2022.11.21
    - name: Code formatting check
      run: nox --session check_code_formatting --force-color
    - name: Static typing check
      run: nox --session check_static_typing --force-color
    - name: Linting
      run: nox --session lint --force-color
    - name: Testing
      id: testing
      run: nox --session run_all_tests --force-color
#    - name: Upload coverage reports to Codecov
#      uses: codecov/codecov-action@v3
    - name: Upload Coverage Report to CodeCov
      if: ${{ steps.testing.conclusion }} == 'success' || ${{ steps.testing.conclusion }} == 'failure' 
      run: nox --sessions upload_coverage_report --force-color
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
